# Gradleプロパティ
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false



# MOD設定
mod_id=xpabilities
mod_name=XP Abilities
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.fumih.xpabilities
mod_authors=fumih
mod_description=経験値を消費してアビリティを習得できるMOD

# マインクラフト・NeoForge バージョン
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
neo_version=21.8.52
neo_version_range=[21.8,)
loader_version_range=[4,)
